---
title: "Quarto Markdown: data sources"
---

## Overview

There are a wide variety of way to make data available to OJS:

- Read CSV, JSON, SQLite, and more using the FileAttachments API.
- Use the ojs_define() function to make data processed in Python or R available to {ojs} cells.
- Make calls to Web APIs for online services and data stores.

We’ll explore all of these *techniques* below.

::: {.callout-tip collapse="false" layout-ncol=2 icon=false}

## File Attachments

[File Attachments](https://quarto.org/docs/interactive/ojs/data-sources.html#file-attachments){#MFile-Attachments}
Use the FileAttachment function from the standard library to read data from a file. For example, here we read and plot a CSV of NOAA’s Monthly CO2 concentration data from Mauna Loa:

```js
data = {
  const co2data = await FileAttachment("co2_mm.csv")
    .csv({ typed: true } );
  return co2data.map(d => {
    d["decimal date"] = Number(d["decimal date"]);
    d.average = Number(d.average);
    return d;
  });
}
Plot.plot({
  marks: [
    Plot.line(data,
      { x: "decimal date", y: "average"},
      { stroke: "black" }
    )
  ]
})
```

:::

::: {.callout-tip collapse="false" layout-ncol=2 icon=false}

## Python and R

[Python and R](https://quarto.org/docs/interactive/ojs/data-sources.html#python-and-r){#MPython-and-R}
The data you want to use with OJS might not always be available in raw form. Often you’ll need to read and preprocess the raw data using Python or R. You can perform this preprocessing during document render (in an {r} or {python} code cell) and then make it available to {ojs} cells via the ojs_define() function.
Here’s an example. We’ll read the same data into R, do some grouping and summarization, then make it available to OJS using ojs_define:

```r
#| output: false

library(readr)
library(dplyr)

co2 = read_csv("co2_mm.csv")  %>%
  group_by(year) %>%
  summarize(max = max(average))

ojs_define(co2data = co2)
```
:::

::: {.callout-tip collapse="false" layout-ncol=2 icon=false}

## Web APIs

[Web APIs](https://quarto.org/docs/interactive/ojs/data-sources.html#web-apis){#Web-APIs}
You can use the d3.json() function to read JSON data from web services and data sources. Here we query the GitHub API for data on contributions to the Python pandas package:

```js
d3 = require('d3')

contributors = await d3.json(
  "https://api.github.com/repos/pandas-dev/pandas/stats/contributors"
)

commits = contributors.map(contributor => {
  const author = contributor.author;
  return {
    name: author.login,
    title: author.login,
    group: author.type,
    value: contributor.total
  }
})
```

:::
